//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceMessages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserAuthorization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserAuthorization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceMessages.Resources.UserAuthorization", typeof(UserAuthorization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get user Email..
        /// </summary>
        public static string CannotGetUserEmail {
            get {
                return ResourceManager.GetString("CannotGetUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Apple token..
        /// </summary>
        public static string InvalidAppleToken {
            get {
                return ResourceManager.GetString("InvalidAppleToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Apple User..
        /// </summary>
        public static string InvalidAppleUser {
            get {
                return ResourceManager.GetString("InvalidAppleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Facebook token..
        /// </summary>
        public static string InvalidFacebookToken {
            get {
                return ResourceManager.GetString("InvalidFacebookToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Facebook User..
        /// </summary>
        public static string InvalidFacebookUser {
            get {
                return ResourceManager.GetString("InvalidFacebookUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Google token..
        /// </summary>
        public static string InvalidGoogleToken {
            get {
                return ResourceManager.GetString("InvalidGoogleToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Google User..
        /// </summary>
        public static string InvalidGoogleUser {
            get {
                return ResourceManager.GetString("InvalidGoogleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not activated. Please activate the user..
        /// </summary>
        public static string UserNotActivated {
            get {
                return ResourceManager.GetString("UserNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/password combination is wrong..
        /// </summary>
        public static string UserOrPasswordWrong {
            get {
                return ResourceManager.GetString("UserOrPasswordWrong", resourceCulture);
            }
        }
    }
}
